FROM node:16.4.0-alpine as builder

WORKDIR /frontend

COPY package.json package-lock.json ./
RUN npm ci --production

COPY public public
COPY src src
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.21.1-alpine

USER nginx

COPY nginx-proxy.conf.template /etc/nginx/templates/default.conf.template
COPY --from=builder --chown=nginx:nginx /frontend/build /var/www/frontend

CMD ["nginx-debug", "-g", "daemon off;"]
