version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        - DJANGO_ALLOWED_HOSTS=localhost api
        - DJANGO_SECRET_KEY
        - DJANGO_CORS_ORIGIN_WHITELIST=http://localhost:8000/
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        API_URL: /api
    ports:
      - 8080:8080
    depends_on:
      - backend
