version: '3'

services:
  backend:
    build:
      context: mysite
    environment:
      PORT: 8000
    env_file: mysite/.env
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  nginx:
    build:
      context: frontend
    environment:
      PORT: 8000
    ports:
      - 8080:8080
    depends_on:
      - backend
