version: '3'

services:
  backend:
    build:
      context: mysite
      dockerfile: Dockerfile.backend
    image: marshmallow.azurecr.io/backend
    container_name: backend
    env_file: mysite/.env
    environment:
      ALLOWED_HOSTS: localhost

  web:
    build:
      context: frontend
      dockerfile: Dockerfile.web
    image: marshmallow.azurecr.io/web
    container_name: web
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
      PORT: 80
    ports:
      - 80:80
    depends_on:
      - backend
