version: '3'

services:
  backend:
    build:
      context: mysite
    image: marshmallow.azurecr.io/backend
    container_name: backend
    environment:
      - ALLOWED_HOSTS=localhost
      - SECRET_KEY
      - DATABASE_URL

  web:
    build:
      context: frontend
    image: marshmallow.azurecr.io/web
    container_name: web
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
      PORT: 80
    ports:
      - 80:80
    depends_on:
      - backend
