version: '3'

services:
  backend:
    build:
      context: mysite
      dockerfile: Dockerfile.backend
    env_file: mysite/.env
    environment: 
      ALLOWED_HOSTS: backend
    command: gunicorn mysite.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  web:
    build:
      context: frontend
      dockerfile: Dockerfile.web
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - backend
