# Generated by Django 3.1.6 on 2021-04-11 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('country_id', models.CharField(default='IL', max_length=2, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('initial_contact_email_address', models.EmailField(max_length=100, null=True)),
                ('job_posting_URL', models.URLField(max_length=250, null=True)),
                ('about_the_job', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('position', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.position')),
            ],
        ),
    ]
