# Generated by Django 3.1.6 on 2021-04-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_applicationprocess_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number2', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='contact',
            field=models.ManyToManyField(null=True, to='myapi.Contact'),
        ),
    ]
