# Generated by Django 3.1.6 on 2021-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210320_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='country',
        ),
        migrations.AddField(
            model_name='position',
            name='country_id',
            field=models.CharField(default='IL', max_length=2, null=True),
        ),
    ]
