# Generated by Django 3.1.6 on 2021-04-02 08:23

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210320_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='country',
            field=django_countries.fields.CountryField(default='Other', max_length=2),
        ),
    ]
