# Generated by Django 3.1.6 on 2021-04-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210402_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='about_the_job',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='initial_contact_email_address',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='job_posting_URL',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
