# Generated by Django 3.1.6 on 2021-04-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210418_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='contact',
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.contact'),
        ),
    ]
