# Generated by Django 3.1.6 on 2021-04-02 08:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210402_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='country',
            field=django_countries.fields.CountryField(max_length=100),
        ),
    ]
