# Generated by Django 3.1.6 on 2021-04-02 08:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210402_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='country',
        ),
        migrations.AddField(
            model_name='position',
            name='country_id',
            field=django_countries.fields.CountryField(default='IL', max_length=2, null=True),
        ),
    ]
