# Generated by Django 3.1.6 on 2021-04-05 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210405_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='applicationprocess',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='position',
            name='user_id',
        ),
        migrations.AddField(
            model_name='applicationprocess',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='applicationprocess',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
