# Generated by Django 3.1.6 on 2021-04-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210405_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.position'),
        ),
    ]
