# Generated by Django 3.1.6 on 2021-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20210418_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, default='main', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='about_the_job',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='country_id',
            field=models.CharField(blank=True, default='IL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='initial_contact_email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_posting_URL',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
