# Generated by Django 3.1.6 on 2021-04-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_applicationprocess_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationprocess',
            old_name='position',
            new_name='posi',
        ),
    ]
