# Generated by Django 3.1.6 on 2021-04-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210410_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationprocess',
            old_name='posi',
            new_name='position',
        ),
    ]
