# Generated by Django 3.1.6 on 2021-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210418_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
