# Generated by Django 3.1.6 on 2021-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_applicationprocess_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='application_process',
            new_name='application_process_url',
        ),
    ]
