# Generated by Django 3.1.6 on 2021-04-11 08:45

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='country_id',
            field=models.CharField(default='IL', max_length=2, null=True, validators=[myapi.models.validate_country_code]),
        ),
    ]
