# Generated by Django 3.1.6 on 2021-04-27 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210426_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('event_type', models.CharField(choices=[('CV', 'cv sent'), ('II', 'initial interview')], default='CV', max_length=2)),
            ],
        ),
    ]
