# Generated by Django 3.1.6 on 2021-04-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='application_process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.applicationprocess'),
        ),
    ]
