# Generated by Django 3.1.6 on 2021-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_stage_application_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
