# Generated by Django 3.1.6 on 2021-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20210427_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='event_type',
            field=models.CharField(choices=[('CV', 'cv sent'), ('II', 'initial interview'), ('HI', 'HR interview'), ('LI', 'team leader interview'), ('MI', 'management interview'), ('OO', 'offer received'), ('NG', 'negotiations'), ('OA', 'offer accepted'), ('OR', 'offer rejected'), ('OT', 'other')], max_length=2),
        ),
    ]
