# Generated by Django 3.1.6 on 2021-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210427_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='event_media',
            field=models.CharField(choices=[('FI', 'F2F'), ('VI', 'video call'), ('PI', 'phone call'), ('EM', 'email'), ('OT', 'other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='stage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='event_type',
            field=models.CharField(choices=[('CV', 'cv sent'), ('II', 'initial interview'), ('HI', 'HR interview'), ('LI', 'team leader interview'), ('MI', 'management interview'), ('OO', 'offer received'), ('NG', 'negotiations'), ('OA', 'offer accepted'), ('OR', 'offer rejected'), ('OT', 'other')], default='OT', max_length=2),
        ),
    ]
