# Generated by Django 3.1.6 on 2021-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_auto_20210710_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('event_type', models.TextField()),
            ],
            options={
                'db_table': 'event_type',
                'managed': False,
            },
        ),
    ]
