# Generated by Django 3.1.6 on 2021-07-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_eventtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={},
        ),
    ]
