# Generated by Django 3.1.6 on 2021-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_auto_20210715_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'managed': False},
        ),
    ]
