# Generated by Django 3.1.6 on 2021-07-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_auto_20210717_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='event_type',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.eventtype'),
        ),
    ]
