# Generated by Django 3.1.6 on 2021-07-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_auto_20210717_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('event_media', models.TextField()),
            ],
            options={
                'db_table': 'event_media',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='stage',
            name='event_media',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.eventmedia'),
        ),
    ]
