# Generated by Django 3.1.6 on 2021-07-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_auto_20210717_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='event_media',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='event_type',
        ),
        migrations.AddField(
            model_name='position',
            name='country',
            field=models.ForeignKey(default='IL', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.countries'),
        ),
        migrations.AlterField(
            model_name='applicationprocess',
            name='status',
            field=models.ForeignKey(default='IN', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.status'),
        ),
    ]
