# Generated by Django 3.1.6 on 2021-07-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_auto_20210717_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='status',
        ),
    ]
