# Generated by Django 3.1.6 on 2021-07-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_remove_applicationprocess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='event_type',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.eventtype'),
        ),
    ]
