# Generated by Django 3.1.6 on 2021-07-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_stage_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='status',
            field=models.ForeignKey(default='IN', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.status'),
        ),
        migrations.AddField(
            model_name='stage',
            name='event_media',
            field=models.ForeignKey(default='OT', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.eventmedia'),
        ),
    ]
