# Generated by Django 3.1.6 on 2021-07-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_auto_20210723_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='note',
        ),
    ]
