# Generated by Django 3.1.6 on 2021-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_remove_applicationprocess_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
