# Generated by Django 3.1.6 on 2021-08-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_applicationprocess_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprocess',
            name='status',
            field=models.ForeignKey(default='IN', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.status'),
        ),
    ]
