# Generated by Django 3.1.6 on 2021-08-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_auto_20210806_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprocess',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='application_process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.applicationprocess'),
        ),
        migrations.AlterField(
            model_name='applicationprocess',
            name='status',
            field=models.ForeignKey(default='IN', on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.status'),
        ),
    ]
