# Generated by Django 3.1.6 on 2021-08-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_auto_20210815_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprocess',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='application_process_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.applicationprocess'),
        ),
    ]
