# Generated by Django 3.1.6 on 2021-08-21 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_auto_20210815_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='country',
        ),
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.AddField(
            model_name='position',
            name='country_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='application_process_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapi.applicationprocess'),
        ),
    ]
