# Generated by Django 3.1.6 on 2021-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_auto_20210822_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, default='main', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='about_the_job',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='country_id',
            field=models.CharField(blank=True, default='IL', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
