# Generated by Django 3.1.6 on 2021-08-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_auto_20210822_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
