# Generated by Django 3.1.6 on 2021-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0037_delete_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
