# Generated by Django 3.1.6 on 2021-09-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0039_document_statsmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsmanager',
            options={'managed': False},
        ),
    ]
