# Generated by Django 3.1.6 on 2021-09-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0040_auto_20210905_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application_process_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.applicationprocess'),
        ),
    ]
