# Generated by Django 3.1.6 on 2021-09-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0041_document_application_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='application_process_id',
        ),
        migrations.AddField(
            model_name='document',
            name='application_process_id',
            field=models.ManyToManyField(to='myapi.ApplicationProcess'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
