# Generated by Django 3.1.6 on 2021-09-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0042_auto_20210905_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
