# Generated by Django 3.1.6 on 2021-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0044_auto_20210905_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
