# Generated by Django 3.1.6 on 2021-09-06 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0047_auto_20210906_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
