# Generated by Django 3.1.6 on 2021-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_process', '0003_auto_20210304_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.AddField(
            model_name='position',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
