name: CI

on:
  push:
    branches: [ main, deployment ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: marshmallow.azurecr.io

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Backend
        id: backend_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./mysite/Dockerfile.backend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  marshmallow.azurecr.io/backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache


      - name: Build and push Frontend
        id: frontend_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./frontend/Dockerfile.frontend
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  marshmallow.azurecr.io/frontend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: |
          echo Backend: ${{ steps.backend_build.outputs.digest }}
          echo Frontend: ${{ steps.frontend_build.outputs.digest }}
